#!/bin/bash
# Set up the test quizzes so that the test suite can be run. This script only needs to
# be run once.

set -e

for arg in "$@"; do
  if test "$arg" = -f; then
    force=yes
  else
    echo "Unrecognized option: $arg"
    echo
    echo "The only supported option is -f, to force overwriting of preexisting quizzes."
    exit 1
  fi
done

if test -e ./target/release/popquiz; then
  quiz=./target/release/popquiz
elif test -e ./target/debug/popquiz; then
  quiz=./target/debug/popquiz
else
  echo "No popquiz executable found in the ./target directory."
  echo "Make sure to run cargo build first."
  exit 2
fi

for path in ./assets/test*; do
  basepath=$(basename "$path")
  name=".${basepath%.*}"
  newpath=$($quiz path -f "$name")

  if test -e "$newpath" && test -z "$force"; then
    echo "Error: quiz '$name' already exists."
    echo
    echo "Re-run with -f to overwrite pre-existing quizzes."
    exit 3
  fi

  echo "Creating quiz '$name'"
  cp "$path" "$newpath"
done
